<?php

namespace CoreBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchTaskByKeyword($content){
        $qb = $this->createQueryBuilder("t");

        $qb->select()
            ->distinct()
            ->where($qb->expr()->like('t.title', '?1'))
            ->orWhere($qb->expr()->like('t.description', '?1'));

        $qb->setParameter(1, "%" . $content . "%");

        return $qb->getQuery()->getResult();
    }
}