app_default:
    resource: "@AppBundle/Resources/config/routing/default.yml"
    prefix: /

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix: /user

app_tasks:
    resource: "@AppBundle/Resources/config/routing/tasks.yml"
    prefix: /tasks

app_task:
    resource: "@AppBundle/Resources/config/routing/task.yml"
    prefix: /task