#core:
#    resource: "@CoreBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check
