#core:
#    resource: "@CoreBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

api_login_check:
    path: /api/login_check
