CoreBundle\Entity\Task:
    type: entity
    table: task
    indexes:
        IDX_527EDB25A76ED395:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        states:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createdat:
            type: time
            nullable: false
            column: createdAt
        updatedat:
            type: time
            nullable: false
            column: updatedAt
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
